TargetFinder/Models/Target/Target.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TargetFinder.Models.Target
{
    public class Target
    {
        public int TargetId { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public decimal Reward { get; set; }
        public string LastLocation { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}

TargetFinder/Controllers/TargetsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TargetFinder.Models;
using TargetFinder.Models.Target;

namespace TargetFinder.Controllers
{
    public class TargetsController : Controller
    {
        private static int currentIDNum;
        private readonly IHostingEnvironment _appEnvironment;
        private readonly TargetFinderContext _context;

        public TargetsController(TargetFinderContext context, IHostingEnvironment environment)
        {
            _appEnvironment = environment;
            _context = context;
        }

        // GET: Targets
        public async Task<IActionResult> Index()
        {
            return View(await _context.Target.ToListAsync());
        }

        // GET: Targets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var target = await _context.Target
                .SingleOrDefaultAsync(m => m.TargetId == id);
            if (target == null)
            {
                return NotFound();
            }

            return View(target);
        }

        // GET: Targets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Targets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TargetId,Name,Alias,Reward,LastLocation,Description")] Target target)
        {
            if (ModelState.IsValid)
            {
                _context.Add(target);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(target);
        }

        // GET: Targets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var target = await _context.Target.SingleOrDefaultAsync(m => m.TargetId == id);
            if (target == null)
            {
                return NotFound();
            }
            return View(target);
        }

        // POST: Targets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TargetId,Name,Alias,Reward,LastLocation,Description")] Target target, IFormFile file)
        {
            if (id != target.TargetId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(target);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TargetExists(target.TargetId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(target);
        }

        // GET: Targets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var target = await _context.Target
                .SingleOrDefaultAsync(m => m.TargetId == id);
            if (target == null)
            {
                return NotFound();
            }

            return View(target);
        }

        // POST: Targets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string path_Root = _appEnvironment.WebRootPath;
            string path_to_Images = path_Root + "\\images\\" + id + ".jpg";
        
            if (System.IO.File.Exists(path_to_Images))
                System.IO.File.Delete(path_to_Images);

            var target = await _context.Target.SingleOrDefaultAsync(m => m.TargetId == id);
            _context.Target.Remove(target);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TargetExists(int id)
        {
            return _context.Target.Any(e => e.TargetId == id);
        }

        [HttpGet] //1.Load

        public IActionResult AddPhoto(int id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var target =  _context.Target.SingleOrDefaultAsync(m => m.TargetId == id);
            if (target == null)
            {
                return NotFound();
            }
            currentIDNum = id;
            //--< Upload Form >--
            return View();
            //--</ Upload Form >--
        }

        [HttpPost] //Postback
        public async Task<IActionResult> AddPhoto(IFormFile file)

        {

            //--------< Upload_ImageFile() >--------

            //< check >
            if (file == null || file.Length == 0) return Content("file not selected");
            //</ check >

            //< get Path >
            string path_Root = _appEnvironment.WebRootPath;
            string path_to_Images = path_Root + "\\images\\" + currentIDNum.ToString() + ".jpg";
            //</ get Path >

            //< Copy File to Target >
            using (var stream = new FileStream(path_to_Images, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            //</ Copy File to Target >

            //< output >
            ViewData["FilePath"] = path_to_Images;
            return RedirectToAction("index");
            //</ output >

            //--------</ Upload_ImageFile() >--------
        }

    }
}

TargetFinder/Views/Targets/AddPhoto.cshtml
@{

        Layout = null;

    }

        <form asp-controller="Targets" asp-action="AddPhoto" method="post"
              enctype="multipart/form-data">



            <input type="file" name="file" />

            <button type="submit">Upload Image</button>

        </form>



        <br />

        <label>Uploaded File= @ViewData["FilePath"]</label>

TargetFinder/Views/Targets/Create.cshtml
@model TargetFinder.Models.Target.Target

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Target</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reward" class="control-label"></label>
                <input asp-for="Reward" class="form-control" />
                <span asp-validation-for="Reward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastLocation" class="control-label"></label>
                <input asp-for="LastLocation" class="form-control" />
                <span asp-validation-for="LastLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                @Html.TextArea("Description", "This is value", new { @class = "form-control", rows = 10, cols = 80 });
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" />
            </div>

        </form> 
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TargetFinder/Views/Targets/Delete.cshtml
@model TargetFinder.Models.Target.Target

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Target</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reward)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reward)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastLocation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastLocation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            <p style="white-space: pre-line">@Model.Description</p>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TargetId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TargetFinder/Views/Targets/Details.cshtml
 @model TargetFinder.Models.Target.Target

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Target</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reward)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reward)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastLocation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastLocation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            <p style="white-space: pre-line">@Model.Description</p>
        </dd>
        <dd>
            @{ var imagePath = "/images/" + Model.TargetId + ".jpg";}
            <img src = @imagePath width="500" height="500"/>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TargetId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TargetFinder/Views/Targets/Edit.cshtml
@model TargetFinder.Models.Target.Target

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Target</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TargetId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reward" class="control-label"></label>
                <input asp-for="Reward" class="form-control" />
                <span asp-validation-for="Reward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastLocation" class="control-label"></label>
                <input asp-for="LastLocation" class="form-control" />
                <span asp-validation-for="LastLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                @Html.TextArea("Description", new { @class = "form-control", rows = 10, cols = 80 });
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TargetFinder/Views/Targets/Index.cshtml
@model IEnumerable<TargetFinder.Models.Target.Target>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Alias)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Reward)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastLocation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Alias)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reward)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastLocation)
            </td>
            <td>
                <p style="white-space: pre-line">@item.Description</p>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TargetId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TargetId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TargetId">Delete</a>
                <a asp-action="AddPhoto" asp-route-id="@item.TargetId">Add Photo</a>
            </td>
        </tr>
}
    </tbody>
</table>